# https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md
config:
  line-length: false # MD013
  no-duplicate-heading: false # MD024
  no-blanks-blockquote: false # MD028 (this warns valid GFM alerts usage)
  no-inline-html: false # MD033
  no-emphasis-as-heading: false # MD036

# https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2jsonc
noBanner: true
noProgress: true
